// frontend-angular/src/app/components/result-card/result-card.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LucideAngularModule, Loader2, Clock } from 'lucide-angular';

@Component({
  selector: 'app-result-card',
  standalone: true,
  imports: [CommonModule, LucideAngularModule],
  templateUrl: './result-card.component.html'
})
export class ResultCardComponent {
  @Input() name: string = '';
  @Input() tag: string = '';
  @Input() dotColor: string = '';
  @Input() barColor: string = '';
  @Input() data: any = null;
  @Input() loading: boolean = false;
  @Input() highlighted: boolean = false;

  readonly Loader2 = Loader2;
  readonly Clock = Clock;
}

<ng-container *ngIf="loading; else contentOrEmpty">
  <div class="rounded-xl border p-4" [ngClass]="highlighted ? 'bg-indigo-50 border-indigo-200/60' : 'bg-white border-slate-200/80'">
    <div class="flex items-center gap-2 mb-3">
      <span class="w-2 h-2 rounded-full" [ngClass]="dotColor"></span>
      <span class="text-xs font-semibold text-slate-800">{{name}}</span>
      <span class="text-[10px] text-slate-500 ml-auto bg-slate-100 px-2 py-0.5 rounded-full">{{tag}}</span>
    </div>
    <div class="space-y-2.5 animate-pulse">
      <div class="h-2 w-16 bg-slate-200 rounded"></div>
      <div class="h-4 w-3/4 bg-slate-200 rounded"></div>
      <div class="h-2 w-16 bg-slate-200 rounded mt-3"></div>
      <div class="h-4 w-full bg-slate-200 rounded"></div>
    </div>
  </div>
</ng-container>

<ng-template #contentOrEmpty>
  <ng-container *ngIf="!data; else resultData">
    <div class="rounded-xl border border-slate-200 bg-white/60 p-5 flex flex-col items-center justify-center text-center h-full min-h-[160px] shadow-sm">
      <lucide-icon [img]="Loader2" class="w-8 h-8 mb-3 opacity-40 animate-spin text-slate-400"></lucide-icon>
      <p class="text-[11px] text-slate-500 font-medium">System ready...</p>
    </div>
  </ng-container>
</ng-template>

<ng-template #resultData>
  <div class="rounded-xl border p-5 flex flex-col transition-all duration-300 shadow-sm"
       [ngClass]="highlighted ? 'bg-indigo-50/80 border-indigo-200 shadow-indigo-100' : 'bg-white border-slate-200/80'">
    <div class="flex items-center gap-2 mb-4">
      <span class="w-2 h-2 rounded-full" [ngClass]="dotColor"></span>
      <span class="text-xs font-bold text-slate-800 tracking-wide">{{name}}</span>
      <span *ngIf="tag" class="text-[10px] ml-auto px-2 py-0.5 rounded-full font-medium"
            [ngClass]="highlighted ? 'bg-indigo-100 text-indigo-700' : 'bg-slate-100 text-slate-600'">{{tag}}</span>
    </div>

    <ng-container *ngIf="data.error; else dataDetails">
      <div class="flex-1 flex flex-col items-center justify-center text-center opacity-75 min-h-[120px] py-4">
        <lucide-icon [img]="Clock" class="w-7 h-7 mb-2.5 text-slate-400 animate-pulse"></lucide-icon>
        <p class="text-xs font-bold text-slate-600">On Progress</p>
        <p class="text-[10px] text-slate-400 mt-1.5 max-w-[180px] leading-relaxed">
          Model integration and validation are currently in progress.
        </p>
      </div>
    </ng-container>

    <ng-template #dataDetails>
      <div class="flex-1 flex flex-col justify-between space-y-4">
        <div>
          <div class="text-[9px] uppercase tracking-wider text-slate-500 font-bold">IC Number</div>
          <div class="text-sm font-semibold mt-1 tracking-wide"
               [ngClass]="!data.nomor_ic ? 'text-slate-400 italic font-normal' : 'text-slate-800'">
            {{data.nomor_ic || 'Not found'}}
          </div>

          <div class="text-[9px] uppercase tracking-wider text-slate-500 font-bold mt-3.5">Address</div>
          <div class="text-xs font-medium mt-1 leading-relaxed"
               [ngClass]="!data.alamat ? 'text-slate-400 italic font-normal' : 'text-slate-700'">
            {{data.alamat || 'Not found'}}
          </div>
        </div>

        <div class="pt-2">
          <div class="flex items-center justify-between text-[10px] text-slate-500 font-medium">
            <span>Confidence</span>
            <span class="font-bold">{{data.confidence}}%</span>
          </div>
          <div class="h-1.5 w-full bg-slate-100 rounded-full mt-1.5 overflow-hidden">
            <div class="h-1.5 rounded-full transition-all duration-1000" [ngClass]="barColor" [ngStyle]="{'width': data.confidence + '%'}"></div>
          </div>
          <div *ngIf="data.processing_ms != null" class="flex items-center justify-end gap-1 text-[9px] text-slate-500 font-semibold mt-2.5">
            <lucide-icon [img]="Clock" class="w-3 h-3"></lucide-icon>
            {{data.processing_ms}} ms
          </div>
        </div>
      </div>
    </ng-template>
  </div>
</ng-template>

// frontend/src/components/ResultCard.jsx
import { Loader2, Clock } from 'lucide-react'

export default function ResultCard({ name, tag, dotColor, barColor, data, loading, highlighted = false }) {
  if (loading) {
    return (
      <div className={`rounded-xl border p-4 ${highlighted ? 'bg-indigo-50 border-indigo-200/60' : 'bg-white border-slate-200/80'}`}>
        <div className="flex items-center gap-2 mb-3">
          <span className={`w-2 h-2 rounded-full ${dotColor}`} />
          <span className="text-xs font-semibold text-slate-800">{name}</span>
          <span className="text-[10px] text-slate-500 ml-auto bg-slate-100 px-2 py-0.5 rounded-full">{tag}</span>
        </div>
        <div className="space-y-2.5 animate-pulse">
          <div className="h-2 w-16 bg-slate-200 rounded" />
          <div className="h-4 w-3/4 bg-slate-200 rounded" />
          <div className="h-2 w-16 bg-slate-200 rounded mt-3" />
          <div className="h-4 w-full bg-slate-200 rounded" />
        </div>
      </div>
    )
  }

  if (!data) {
    return (
      <div className="rounded-xl border border-slate-200 bg-white/60 p-5 flex flex-col items-center justify-center text-center h-full min-h-[160px] shadow-sm">
        <Loader2 className="w-8 h-8 mb-3 opacity-40 animate-spin text-slate-400" />
        <p className="text-[11px] text-slate-500 font-medium">System ready...</p>
      </div>
    )
  }

  const { nomor_ic, alamat, confidence, processing_ms, error } = data

  return (
    <div className={`rounded-xl border p-5 flex flex-col transition-all duration-300 shadow-sm ${
      highlighted 
        ? 'bg-indigo-50/80 border-indigo-200 shadow-indigo-100' 
        : 'bg-white border-slate-200/80'
    }`}>
      <div className="flex items-center gap-2 mb-4">
        <span className={`w-2 h-2 rounded-full ${dotColor}`} />
        <span className="text-xs font-bold text-slate-800 tracking-wide">{name}</span>
        {tag && (
          <span className={`text-[10px] ml-auto px-2 py-0.5 rounded-full font-medium ${
            highlighted ? 'bg-indigo-100 text-indigo-700' : 'bg-slate-100 text-slate-600'
          }`}>{tag}</span>
        )}
      </div>

      {error ? (
        <div className="flex-1 flex flex-col items-center justify-center text-center opacity-75 min-h-[120px] py-4">
          <Clock className="w-7 h-7 mb-2.5 text-slate-400 animate-pulse" />
          <p className="text-xs font-bold text-slate-600">On Progress</p>
          <p className="text-[10px] text-slate-400 mt-1.5 max-w-[180px] leading-relaxed">
            Model integration and validation are currently in progress.
          </p>
        </div>
      ) : (
        <div className="flex-1 flex flex-col justify-between space-y-4">
          <div>
            <div className="text-[9px] uppercase tracking-wider text-slate-500 font-bold">IC Number</div>
            <div className={`text-sm font-semibold mt-1 tracking-wide ${!nomor_ic ? 'text-slate-400 italic font-normal' : 'text-slate-800'}`}>
              {nomor_ic || 'Not found'}
            </div>

            <div className="text-[9px] uppercase tracking-wider text-slate-500 font-bold mt-3.5">Address</div>
            <div className={`text-xs font-medium mt-1 leading-relaxed ${!alamat ? 'text-slate-400 italic font-normal' : 'text-slate-700'}`}>
              {alamat || 'Not found'}
            </div>
          </div>

          <div className="pt-2">
            <div className="flex items-center justify-between text-[10px] text-slate-500 font-medium">
              <span>Confidence</span>
              <span className="font-bold">{confidence}%</span>
            </div>
            <div className="h-1.5 w-full bg-slate-100 rounded-full mt-1.5 overflow-hidden">
              <div className={`h-1.5 rounded-full transition-all duration-1000 ${barColor}`} style={{ width: `${confidence}%` }} />
            </div>
            {processing_ms != null && (
              <div className="flex items-center justify-end gap-1 text-[9px] text-slate-500 font-semibold mt-2.5">
                <Clock className="w-3 h-3" />
                {processing_ms} ms
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  )
}
