// frontend/src/components/ConsensusBanner.jsx
import { CheckCircle2, AlertTriangle } from 'lucide-react'

export default function ConsensusBanner({ consensus }) {
  if (!consensus) return null

  const { agreement, nomor_ic } = consensus

  return (
    <div
      className={`flex items-center gap-3 text-xs px-4 py-3 rounded-xl border shadow-sm ${
        agreement 
          ? 'bg-emerald-50 border-emerald-200 text-emerald-700' 
          : 'bg-amber-50 border-amber-200 text-amber-700'
      }`}
    >
      {agreement ? <CheckCircle2 className="w-4 h-4" /> : <AlertTriangle className="w-4 h-4" />}
      <span className="font-semibold tracking-wide">
        {agreement
          ? `Consensus Achieved — All systems matched IC: ${nomor_ic}`
          : 'Consensus Mismatch — Systems returned differing IC values. Review manually.'}
      </span>
    </div>
  )
}

// frontend-angular/src/app/components/consensus-banner/consensus-banner.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LucideAngularModule, CheckCircle2, AlertTriangle } from 'lucide-angular';

@Component({
  selector: 'app-consensus-banner',
  standalone: true,
  imports: [CommonModule, LucideAngularModule],
  templateUrl: './consensus-banner.component.html'
})
export class ConsensusBannerComponent {
  @Input() consensus: { agreement: boolean; nomor_ic: string | null } | null = null;

  readonly CheckCircle2 = CheckCircle2;
  readonly AlertTriangle = AlertTriangle;
}

<div *ngIf="consensus"
     class="flex items-center gap-3 text-xs px-4 py-3 rounded-xl border shadow-sm"
     [ngClass]="consensus.agreement ? 'bg-emerald-50 border-emerald-200 text-emerald-700' : 'bg-amber-50 border-amber-200 text-amber-700'">
  <lucide-icon *ngIf="consensus.agreement" [img]="CheckCircle2" class="w-4 h-4"></lucide-icon>
  <lucide-icon *ngIf="!consensus.agreement" [img]="AlertTriangle" class="w-4 h-4"></lucide-icon>
  <span class="font-semibold tracking-wide">
    <ng-container *ngIf="consensus.agreement">
      Consensus Achieved — All systems matched IC: {{consensus.nomor_ic}}
    </ng-container>
    <ng-container *ngIf="!consensus.agreement">
      Consensus Mismatch — Systems returned differing IC values. Review manually.
    </ng-container>
  </span>
</div>
